server:
  port: 8080

spring:
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/shiro-db
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver